#pragma once
/**
Compile the source data into the arduino application
This file will be generated by python from the parsed data
*/
namespace data{
	const int numSensors = 1;
	const int numValues = 5;
	const float raw[numSensors][numValues] = {
						{1.0, 50.0, 20.0, 200.0, 5.0},
						};
}